.define THREAD_COUNT 4
.define STACK_SIZE 500
.define DEBUG 1

.ifdef DEBUG
.define DEBUG_PRINT SYSCALL PRN
.else
.define DEBUG_PRINT # No debug output
.endif

#GTU-C312 Test Program with Preprocessor Directives
Begin Data Section
$PC 100
$SP 1000
$SYSCALL_RES 0
$INSTR_COUNT 0
$TEMP1 0
$TEMP2 0
$PARAM1 0
$PARAM2 0
$ZERO 0
$FP 0
@KERNEL_START SENTINEL_DEAD
@THREAD_TABLE_BASE 40
@THREAD1_START 1000
@THREAD2_START 2000
THREAD_COUNT THREAD_COUNT
STACK_SIZE STACK_SIZE
End Data Section

Begin Instruction Section
# Test preprocessor symbol expansion
100 SET 0 $ZERO
101 SET 1 @OS_STATE
102 SET THREAD_COUNT @THREAD_COUNT
103 SET @THREAD1_START $PARAM1
104 DEBUG_PRINT @OS_STATE
105 CPY $PARAM1 $TEMP1
106 ADD $TEMP1 STACK_SIZE
107 SYSCALL PRN $TEMP1
108 HLT
End Instruction Section
